# The main "setup" workflow, that calls other workflows.
name: Docker Images Build

on: [push]

permissions:
  contents: read

# Agent Docker image tests
#
# To test this workflow with your branch, make the following changes:
#
# 1. In this workflow, change ``@master`` to ``@your_branch_name`` - e.g. ``@docker_image_alpine``

# 2. In this workflow, change docker hub secrets to utilize testing and not prod account so images
#    get pushed to testing account. Change ``_PROD_` in the secret name to ``_TEST``,
#    e.g. ``DOCKER_HUB_USERNAME_TEST_ACCOUNT`` ``DOCKER_HUB_PASSWORD_TEST_ACCOUNT``.
#    Images for test account will get pushed to https://hub.docker.com/r/test4scalyr/.
#
# 3. In the job 'publish-images' below, change 'refs/heads/improve-caching-test' in the job conditional to you current branch.:
#
# For example: https://github.com/scalyr/scalyr-agent-2/pull/804/commits/0eccf278623552b51d9289d75a47794e88f02862
jobs:
  test-images:
    #runs-on: windows-2019
    runs-on: ubuntu-20.04

    strategy:
      matrix:

        python-version: [ "3.8.13" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          dockerfile: Dockerfile
          tags: tambel/ubu:latest
          context: .
          push: false
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

#      - name: Install python
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}



      - name: Run image build
        run: |
          docker buildx build -t tambel/test -f Dockerfile .
          docker push tambel/test






